trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.0.0'  # specify your desired Terraform version

steps:
- task: MicrosoftDefenderForCloud.MSDO@0
  inputs:
    command: 'run'  # Choose from 'run', 'pre-job', 'post-job'
    config: 'path/to/your/config.gdnconfig'  # Optional: Specify the path to your MSDO config file
    policy: 'azuredevops'  # Choose from 'azuredevops', 'microsoft', 'none'
    categories: 'IaC,secrets'  # Optional: Specify categories like 'secrets', 'code', etc.
    languages: 'javascript,typescript'  # Optional: Specify languages to analyze
    tools: 'terrascan,trivy'  # Optional: Specify tools like 'bandit', 'binskim', etc.
    break: false  # Set to true if you want to fail the build on error results
    publish: true  # Set to true to publish SARIF results
    artifactName: 'CodeAnalysisLogs'  # Optional: Specify the artifact name for SARIF results

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'terrafromiacdevops1'
    backendAzureRmResourceGroupName: 'test-grp'
    backendAzureRmStorageAccountName: 'regterraformstate201'
    backendAzureRmContainerName: 'tfstatefiles'
    backendAzureRmKey: 'az-devops-kubernetes-terraform.tfstate'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'terrafromiacdevops1'

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'terrafromiacdevops1'


