trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  terraformVersion: '1.0.0'  # specify your desired Terraform version
  serviceConnectionName: $(service_conn_name) # Assuming this is set in your pipeline settings as a secret

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnectionName) # Replace with your actual service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Logging in to Azure"
      az account show

- script: |
    echo "Install Terraform"
    wget https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip
    unzip terraform_$(terraformVersion)_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- script: |
    echo "Initializing Terraform"
    terraform init
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Terraform Init'

- script: |
    echo "Generating Terraform Plan"
    terraform plan
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Terraform Plan'

- script: |
    echo "Applying Terraform"
    terraform apply -auto-approve
  workingDirectory: '$(System.DefaultWorkingDirectory)'
  displayName: 'Terraform Apply'


