trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Install Terraform"
    wget https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
    unzip terraform_0.12.24_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'

- script: |
    echo "Initializing Terraform"
    terraform init
  displayName: 'Terraform Init'


- script: |
    echo "Validating Terraform"
    terraform plan
  displayName: 'Terraform Plan'

- script: |
    echo "Applying Terraform"
    terraform apply -auto-approve
  displayName: 'Terraform Apply'

